spring:
 application:
  name: twitter-to-kafka-service
 profiles:
  active: dev
 config:
  import: optional:configserver:http://localhost:8888  
 cloud:
  config:
   name: twitter-to-kafka-service,config-client	
   username: spring_cloud_user
   password: Sam8899
         

