spring:
 profiles:
  #active: native,dev
  active: dev
 application:
  name: configserver
 cloud:
  config:
   server:
    #native:
     #search-locations: file:///H:/2023_Tech/2202_03_workspace/microservices-demo/config-server-repository
     #clone-on-start: true
    git:
     uri: https://github.com/keatchong/spring-cloud-config-server-repository
     username: keatmin@gmail.com
     password: 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
     clone-on-start: true
   fail-fast: true   
 security:
  user:
   name: spring_cloud_user
   password: '{cipher}236bd0e922720314c170c3a6311b21b87dd97a84da86fcac804b5ead2fbf0c10df2cf1c754f1c8be339754163d6708fc'
   
server:
 port: 8888
  
logging:
 level:
  ROOT: DEBUG
  org.springframework.cloud.config: DEBUG
     
encrypt:
 key: 'Demo_Pwd!2020'

 