spring:
 profiles:
  #active: native,dev
  active: dev
 application:
  name: configserver
 cloud:
  config:
   server:
    #native:
     #search-locations: file:///H:/2023_Tech/2202_03_workspace/microservices-demo/config-server-repository
     #clone-on-start: true
    git:
     uri: https://github.com/keatchong/spring-cloud-config-server-repository
     username: keatmin@gmail.com
     password: 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
     clone-on-start: true
   fail-fast: true   
 security:
  user:
   name: spring_cloud_user
   password: Sam8899
   
server:
 port: 8888
  
logging:
 level:
  ROOT: DEBUG
  org.springframework.cloud.config: DEBUG
     
#encrypt:
 #key: 'Demo_Pwd!2020'

 