spring:
 application:
  name: configserver
 cloud:
  config:
   server:
    #native:
     #search-locations: file:///H:/2023_Tech/2202_03_workspace/microservices-demo/config-server-repository
     #clone-on-start: true
    git:
     uri: https://github.com/agelenler/spring-cloud-config-server-repository
     default-label: main
     username: agelenler
     password: 'xxx'
     clone-on-start: true
   fail-fast: true   
 security:
  user:
   name: spring_cloud_user
   password: '{cipher}1f83997bb42ee71476345bdb9756680a86799988ee14cad8fba98ac520ac4a03'
   
server:
 port: 8888
  
logging:
 level:
  ROOT: INFO
  org.springframework.cloud.config: INFO

encrypt:
 key: 'Demo_Pwd!2020'

 